name: distribuplus
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
